// Augments the `env` exported from "cloudflare:test" with our Worker bindings,
// so tests see `env.PRICES` typed. `Env` is generated by `wrangler types`
// (worker-configuration.d.ts). Re-run `wrangler types` after changing bindings.
declare module "cloudflare:test" {
  interface ProvidedEnv extends Env {}
}
